services:
  api:
    container_name: api-mlali-fastapi
    build: .
    command: sh -c "uvicorn api:app --host=0.0.0.0 --port 6001 --workers 8"
    env_file:
      - .env
    ports:
      - "6001:6001"
    restart: always
    volumes:
      - .:/app
